services:
  - type: web
    name: pawsense-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 8000
      - key: ALLOWED_ORIGINS
        value: https://pawsense-ui.onrender.com
      - key: MODEL_PATH
        value: models/breed_model/mobilenetv2_dogbreeds.pth
    healthCheckPath: /api/health 